travis:
  secure:
    BINSTAR_TOKEN: QwUqWJQMoujUzrpi13pXxUMrujRNtSZDzSTDAfPfFSKAuDj4iM43IW49waCVgFNMof+6gkYog0GCmYntndC/H/09jIPNMhehxRADCrYkrKtFWSMISyA1Urdc2G113AdKyOLZ3jkUEqFDyuTjU6syIcsifRCibp8dc+W7fuudVxpk8QAomCS7d51YcaSigY/TAaS64yCZ9gLCNOrd++t8VnrzGKfnTzJ52sGnisesgNWKqv8XHIh1bxczWvSi9/EU3+tVKuFF2e9IaEATcVRvkKvkXOQv2I4WFO8kG1+j1JF95OgPNveUQCGaAISjZcveO3XcOhSIb69SAtldqn7qR/hASCeUkWMiu5axTKYuokIDUDvP5SgZ5c6pP2/fULZmsUzo+fZUnf2j1fLdU6OqwkYFxKT3veA9Xniqws1xNq0mpxZsMHWAuuVzQLV3gqO0PwAIlSxl582RvH9JdwJ9uK2XBVky7pZb3gpzUL9ALlQOswF6uPWnXceMEic5G9tQjRcSycrV03UOUWSw5qZMmDKpnpxKJ43UOhFOUsuetlU/ususg4G0YDlb3ivSYc+VXOlPZhZE/cSiYsNPiAzCG7/E1wzaM6res2zioKzkDImU/3G2x5QOdxm/ZHGoxC1i3PxF+ymUYTtPHKNFztxdCr+tWb4gWegkH9ZaCouF3CQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
